packages:
  # all packages in direct subdirs of packages/
  # 个人翻译： 存放你得具体web项目
  - 'packages/*'
  # all packages in subdirs of components/
  # 个人翻译： 存放公用组件
  - 'components/**'
  # common api
  - "api/**"
